apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip
spec:
  type: ClusterIP  # Default type (optional to write)
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80          # Exposed port inside cluster
      targetPort: 3000  # Port your container listens on
