apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:                        
    path: /tmp/k8s-cache           
